### ISSUE TITLE
Unable to view p!stats

### ISSUE THREAD

**Issue by Juliacare** [pinano-discord/Pinano-Discord-Bot#124]
![image](https://user-images.githubusercontent.com/36482621/68550648-e06f6b00-0404-11ea-97d9-e8e951eb6464.png)

(See error message above)

User squishy#2552 used the p!stats command and was returned a null error.
The commands were used around 4-5 minutes prior to posting this in case anyone wants to check logs.

**Comment by pianiststickman** [comment]
RCA: new users may not have `recitals` property set.

Fix: put in a null check on recitals.

**Comment by pianiststickman** [comment]
Fixed: #125
