### ISSUE TITLE
Ideas for more badges

### ISSUE THREAD

**Issue by pianiststickman** [pinano-discord/Pinano-Discord-Bot#142]
- silent badge: was part of a mute party of n people
- rickrolled by PB (this requires an audio setup)
- stalker badge: run stats on other people n times
- even numbers badge: my practice session was EXACTLY a multiple of 3600
- special rooms for occasions (e.g. Christmas, April 1)
- badges for listening

**Comment by Juliacare** [comment]
emoji suggestions for badges:

Silent badge: :speak_no_evil: 
Stalker badge: :detective: 
Listening: :headphones:

**Comment by pianiststickman** [comment]
I was just gonna use 🔇 for the mute badge.

Agreed on the other two.

**Comment by Juliacare** [comment]
With the daily time feature, daily badges perhaps?
Something like 4 hours, 8 hours, 12 hours (and not higher to not promote masochistism)
