### ISSUE TITLE
Go live permission handling

### ISSUE THREAD

**Issue by Juliacare** [pinano-discord/Pinano-Discord-Bot#168]
Deny `go live` on default for practice rooms and grant the permission to the person whoever owns the lock of said voice channel.

**Comment by Juliacare** [comment]
see https://discordapp.com/developers/docs/topics/permissions
its named `STREAM`

**Comment by pianiststickman** [comment]
STREAM is not implemented in discord.js. Is this actually an issue? If someone goes live in a locked room but is muted anyway, do we need to prevent that?

**Comment by Juliacare** [comment]
> If someone goes live in a locked room but is muted anyway, do we care?

yes as the person's mic is muted, their livestream will still be audible. 
I do the same with the watchtogether event, where I'm muted yet everyone can still hear my stream.

**Comment by pianiststickman** [comment]
What happens if they are server muted?

**Comment by Juliacare** [comment]
then they can still `go live` however not screenshare without going live. So it wont be a direct interference from another audio source however it does look weird / a little misleading to have someone be live (Streaming whatever) in the same channel someone is practicing.

**Comment by Juliacare** [comment]
Closing issue until it actually becomes an issue
