### ISSUE TITLE
IMSLP search function

### ISSUE THREAD

**Issue by Juliacare** [pinano-discord/Pinano-Discord-Bot#185]
Cira probably dropped the feature but might be fun to imploment anyway, perhaps we could ask her for her clone so you dont have to start from square 1.

`Sheet music search function eg using imslp.org as a search engine and linking results`

**Comment by pianiststickman** [comment]
Quick triage comment: not sure if this solves an actual problem. Significant UX questions regarding clutter. Significant effort for little value, IMO - browsers are still a thing.
