### ISSUE TITLE
Settings command seems broken

### ISSUE THREAD

**Issue by Juliacare** [pinano-discord/Pinano-Discord-Bot#28]
Somewhere somehow the settings command got broken. Two practice rooms Project added yesterday didn't go through and it seems I'm also not able to add them through text commands.

The issue was observed around 11:30 am CET 19th of February.

Chat logs: https://pastebin.com/GnqZ62Dp

**Comment by pianiststickman** [comment]
Not able to repro. Keeping this open so we can add proper logging for things.

**Comment by pianiststickman** [comment]
Being able to dump the current list of channels would also be good too.

**Comment by pianiststickman** [comment]
`p!settings` deprecated. `p!rooms` should satisfy the current diagnostic need.
