### ISSUE TITLE
Self assignable roles

### ISSUE THREAD

**Issue by Juliacare** [pinano-discord/Pinano-Discord-Bot#86]
To replace Dyno colour roles for regulars,
To give Craig role for regulars,
To give classical, non-classical for everyone

**Comment by pianiststickman** [comment]
Dyno updated with the `?craig` command. Holding off on classical/non-classical roles for now while we figure out if we really want the roles at all

**Comment by Juliacare** [comment]
Classical and non-classical roles now are the pingable roles for the question of the week. 
Taking off priority tag as we have a temp solution through Dyno.
@pianiststickman perhaps you can make the two self assignable through dyno as well in the mean time?

**Comment by pianiststickman** [comment]
Done.

`?classical` and `?non-classical` toggle the roles and are assignable by everybody.
`?craig` remains toggle-able by regulars only.
