### ISSUE TITLE
Use cards instead of raw text for leaderboards

### ISSUE THREAD

**Issue by Juliacare** [pinano-discord/Pinano-Discord-Bot#87]
see https://github.com/pinano-discord/Pinano-Discord-Bot/blob/master/assets/overall_leaderboard.png 
and https://github.com/pinano-discord/Pinano-Discord-Bot/blob/master/assets/weekly_leaderboard.png

**Comment by pianiststickman** [comment]
So the real question is - do we want to actually do this? Jimp doesn't seem to support Unicode which means that the leaderboard is just going to have "?????" for Unicode usernames.

**Comment by Juliacare** [comment]
I feel like we don't have that many people with names like that and its really up to them that theyre not showing on the leaderboard. They can always swap back to a normal character username if they want to be shown on the leaderboard again with their name.

**Comment by pianiststickman** [comment]
A unicode font would be the best solution, I think. Basically we have a situation where Discord supports unicode but jimp doesn't. So when we moved p!stats to an image, we lost unicode support. If we could avoid ripping out unicode support for the leaderboard too it'd be preferable - the last thing I really want to try to do is figure out what sequence of question marks represents which user.

**Comment by Juliacare** [comment]
Note for anyone reading back:
Fixing #53 will fix this issue

**Comment by pianiststickman** [comment]
See discussion in #78

**Comment by pianiststickman** [comment]
Problem solved a different way.
