### ISSUE TITLE
Count literature quiz correct guesses

### ISSUE THREAD

**Issue by Juliacare** [pinano-discord/Pinano-Discord-Bot#92]
Add more flair to the stat card by putting in a counter for amount of quiz questions you correctly answered. 

Todo:
Add a command p!addpoint @user#1234 (Usable by mods?)
Add a command p!delpoint @user#1234 (Usable by mods?)
Change stat card again to include a counter of total quiz geusses

**Comment by pianiststickman** [comment]
Needs coherent policy on what is actually a correct guess. (Do hints count?)

**Comment by Juliacare** [comment]
I'd say only the first person to actually geuss the piece name, perhaps we should take this up for discussion in #moderator-room

**Comment by pianiststickman** [comment]
Looks like we need to enforce a queue, too.

**Comment by pianiststickman** [comment]
Quiz module added in #131
